version: '3'
services:
    a1:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ./bricks/a1:/data

    a2:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ./bricks/a2:/data
    a3:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ./bricks/a3:/data

    m1:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ./bricks/m1:/data
        ports:
            - 24007:24007

    m2:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ./bricks/m2:/data

    m3:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ./bricks/m3:/data
