# agsm    <-> gwa <-> gwm <-> meucci
# 172.16.15.0/26  <-> 172.16.15.64/26 <-> 172.16.15.128/26
# 172.16.15.11-13 ---agsm--- 172.16.15.62-172.16.15.66 ---internet--- 172.16.15.67-172.16.15.190 ---meucci---  172.16.15.131-133

version: '3'
services:
    a1:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ${BRICKS}/a1:/data
            - ./hosts:/etc/hosts
        environment:
            - GW=172.16.15.62
        networks:
            agsm:
                ipv4_address: 172.16.15.11
        # ports:
        #     - 24007:24007
        #     - 24008:24008
        #     - 49152:49152
        #     - 49153:49153
        #     - 49154:49154
        #     - 49155:49155
        #     - 49156:49156
        #     - 49157:49157
    a2:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ${BRICKS}/a2:/data
            - ./hosts:/etc/hosts
        environment:
            - GW=172.16.15.62
        networks:
            agsm:
                ipv4_address: 172.16.15.12
    a3:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ${BRICKS}/a3:/data
            - ./hosts:/etc/hosts
        environment:
            - GW=172.16.15.62
        networks:
            agsm:
                ipv4_address: 172.16.15.13
    gwa:
        image: ${IMAGE}
        privileged: true
        environment:
            - ROUTE=172.16.15.128/26 via 172.16.15.67
        networks:
            agsm:
                ipv4_address: 172.16.15.62
            internet:
                ipv4_address: 172.16.15.66

    gwm:
        image: ${IMAGE}
        privileged: true
        environment:
            - ROUTE=172.16.15.0/26 via 172.16.15.66
        networks:
            meucci:
                ipv4_address: 172.16.15.190
            internet:
                ipv4_address: 172.16.15.67
    m1:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ${BRICKS}/m1:/data
            - ./hosts:/etc/hosts
        environment:
            - GW=172.16.15.190
        networks:
            meucci:
                ipv4_address: 172.16.15.131
    m2:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ${BRICKS}/m2:/data
            - ./hosts:/etc/hosts
        environment:
            - GW=172.16.15.190
        networks:
            meucci:
                ipv4_address: 172.16.15.132
    m3:
        image: ${IMAGE}
        privileged: true
        volumes:
            - ${BRICKS}/m3:/data
            - ./hosts:/etc/hosts
        environment:
            - GW=172.16.15.190
        networks:
            meucci:
                ipv4_address: 172.16.15.133

    kvm:
        image: galileo/kvm
        privileged: true
        build:
            context: ./docker
            dockerfile: Dockerfile.kvm
            args:
                GW: 172.16.15.62
        networks:
            - agsm
        volumes:
            - ./hosts:/etc/hosts
            - ./vms:/vms
networks:
    agsm:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.15.0/26
    internet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.15.64/26
    meucci:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.15.128/26
