#!/usr/bin/env bash

dir=$(pwd)

MASTER=m1
HOSTS="a1 a2 a3 m1 m2 m3"

function :build {
  docker build -t galileo/glusterfs ./docker
  docker compose build kvm
}

function :start {
  docker-compose up --remove-orphans
}

function :cli {
  docker-compose run --rm -it $1 bash
}

function :exec {
  docker-compose exec $1 $2
}

function :destroy {
  docker-compose down
  sudo rm -fR ./runtime/bricks
}

function :boot {
  :destroy
  docker-compose up --remove-orphans -d
  sleep 5

  # probe peer hosts
  for host in $HOSTS; do
    echo "peer host $host"
    docker-compose exec $MASTER gluster peer probe $host
  done

  docker-compose exec $MASTER gluster volume create gv0 replica 2 a1:/data/brick1 m1:/data/brick1 a2:/data/brick1 m2:/data/brick1 a3:/data/brick1 m3:/data/brick1 force
  sleep 1
  docker-compose exec $MASTER gluster volume set gv0 server.allow-insecure on
  #gluster volume set <vol-name> storage.owner-uid 107
  #gluster volume set <vol-name> storage.owner-gid 107
  docker-compose exec $MASTER gluster volume start gv0

  # mount volume on each node in /mnt/gv0
  for host in $HOSTS; do
    docker-compose exec $host mkdir -p /mnt/gv0
    docker-compose exec $host mount -t glusterfs localhost:/gv0 /mnt/gv0
  done

  :test normal
}

function :test {
  test=$1

  echo
  for host in ${HOSTS}; do
    echo "create file on $host: /mnt/gv0/$host-$test.txt"
    #docker-compose exec $host truncate -s 10m /mnt/gv0/example-$test-$host.txt
    docker-compose exec $host bash -c "echo -n $host-$test_`date +'%H:%M:%S'`'; '  >> /mnt/gv0/$host-$test.txt"
  done

  # check
  echo
  tree -h runtime/bricks
}

function :check {
  for host in $HOSTS; do
    echo "$host: "
    docker-compose exec $host bash -c 'for i in /mnt/gv0/*; do echo -n $i ": "; cat $i; echo ; done'
    echo "-----------------------------"
  done
}

function :expand {
  # aggiungiamo dei nuovi brick (ovvero volumi openstack)
  docker-compose exec $MASTER gluster volume add-brick gv0 replica 2 wa2:/data/brick2 wm2:/data/brick2
  docker-compose exec $MASTER gluster volume rebalance gv0 start
}

function :meucci:disconnect {
  echo "disconnect meucci from agsm: no internet connection between sites"
  docker-compose exec gwm sh -c "echo 0 > /proc/sys/net/ipv4/ip_forward"
}

function :meucci:connect {
  echo "reconnecting meucci"
  docker-compose exec gwm sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
}

function :meucci:kill {
  docker compose kill m1
  docker compose kill m2
  docker compose kill m3
}

function :meucci:start {
  docker-compose up m1 m2 m3 -d
  sleep 5
  for host in m1 m2 m3; do
    docker-compose exec $host mkdir -p /mnt/gv0
    docker-compose exec $host mount -t glusterfs localhost:/gv0 /mnt/gv0
  done
}

function :status {
  docker-compose exec $MASTER gluster vol info
  docker-compose exec $MASTER gluster vol status
  docker-compose exec $MASTER gluster peer status
}

function :vm:create {
  # copiamo l'immagine backing su gluster
  docker-compose exec kvm mount -t glusterfs $MASTER:/gv0 /mnt
  docker-compose exec kvm cp -v /vms/jammy-server-cloudimg-amd64-disk-kvm.img /mnt/
  docker-compose exec kvm umount /mnt

  # creaiamo una immagine jammy.qcow2 da 10G con backing quella ufficiale
  qemu-img create -f qcow2 -F qcow2 -b gluster://a1/gv0/jammy-server-cloudimg-amd64-disk-kvm.img gluster://a1/gv0/jammy.qcow2 10G
  
  # creiamo la vm
  docker-compose exec kvm virsh destroy ubuntu >/dev/null 2>&1 
  docker-compose exec kvm virsh undefine ubuntu >/dev/null 2>&1 
  docker-compose exec kvm virsh define /vms/ubuntu.xml
  docker-compose exec kvm virsh start ubuntu
}

function :vm:dowload {
  IMAGE=jammy-server-cloudimg-amd64-disk-kvm.img
  if [ ! -f ./vms/$IMAGE ]; then
    mkdir -p vms
    cd vms
    wget http://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img \
    && virt-customize -a vms/jammy-server-cloudimg-amd64-disk-kvm.img --root-password password:root
    #qemu-img create -f qcow2 -b $IMAGE jammy.qcow2 10G
    echo 'customized ubuntu with password root un user root'
  fi
}

function :vm:cidata {
  cd vms
  genisoimage -output cidata.iso -V cidata -r -J user-data meta-data
}

function :help {
  echo "$0 <task> <args>"
  echo "Tasks:"

  # We pick out the `:*` functions
  compgen -A function | sed -En 's/(.*):(.*)/\1:\2/p' | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ":${@:-help}"

