#!/usr/bin/env bash

dir=$(pwd)

MASTER=m1
HOSTS="a1 a2 a3 m1 m2 m3"

function :build {
  docker build -t galileo/glusterfs ./docker
}

function :start {
  docker-compose up --remove-orphans
}

function :cli {
  docker-compose run --rm -it $1 bash
}

function :exec {
  docker-compose exec $1 $2
}

function :destroy {
  docker-compose down
  sudo rm -fR ./bricks
}

function :boot {
  :destroy
  docker-compose up --remove-orphans -d
  sleep 5

  # probe peer hosts
  for host in $HOSTS; do
    echo "peer host $host"
    docker-compose exec $MASTER gluster peer probe $host
  done

  docker-compose exec $MASTER gluster volume create gv0 replica 2 a1:/data/brick1 m1:/data/brick1 a2:/data/brick1 m2:/data/brick1 a3:/data/brick1 m3:/data/brick1 force
  sleep 1
  docker-compose exec $MASTER gluster volume start gv0

  # mount volume on each node in /mnt/gv0
  for host in $HOSTS; do
    docker-compose exec $host mkdir -p /mnt/gv0
    docker-compose exec $host mount -t glusterfs localhost:/gv0 /mnt/gv0
  done

  :test normal
}

function :test {
  test=$1

  echo
  for host in ${HOSTS}; do
    echo "create file on $host: /mnt/gv0/$host-$test.txt"
    #docker-compose exec $host truncate -s 10m /mnt/gv0/example-$test-$host.txt
    docker-compose exec $host bash -c "echo -n $host-$test_`date +'%H:%M:%S'`'; '  >> /mnt/gv0/$host-$test.txt"
  done

  # check
  echo
  tree -h bricks
}

function :check {
  for host in $HOSTS; do
    echo "$host: "
    docker-compose exec $host bash -c 'for i in /mnt/gv0/*; do echo -n $i ": "; cat $i; echo ; done'
    echo "-----------------------------"
  done
}

function :expand {
  # aggiungiamo dei nuovi brick (ovvero volumi openstack)
  docker-compose exec $MASTER gluster volume add-brick gv0 replica 2 wa2:/data/brick2 wm2:/data/brick2
  docker-compose exec $MASTER gluster volume rebalance gv0 start
}

function :meucci:disconnect {
  echo "disconnect meucci from agsm: no internet connection between sites"
  docker-compose exec gwm sh -c "echo 0 > /proc/sys/net/ipv4/ip_forward"
}

function :meucci:connect {
  echo "reconnecting meucci"
  docker-compose exec gwm sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
}

function :meucci:kill {
  docker compose kill m1
  docker compose kill m2
  docker compose kill m3
}

function :meucci:start {
  docker-compose up m1 m2 m3 -d
  sleep 5
  for host in m1 m2 m3; do
    docker-compose exec $host mkdir -p /mnt/gv0
    docker-compose exec $host mount -t glusterfs localhost:/gv0 /mnt/gv0
  done
}

function :status {
  docker-compose exec $MASTER gluster vol info
  docker-compose exec $MASTER gluster vol status
  docker-compose exec $MASTER gluster peer status
}

function :help {
  echo "$0 <task> <args>"
  echo "Tasks:"

  # We pick out the `:*` functions
  compgen -A function | sed -En 's/(.*):(.*)/\1:\2/p' | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ":${@:-help}"

